### ISSUE TITLE
sample.py

### ISSUE THREAD

**Issue by jherfson** [Levi-UFMA/levi-utils#1]
@lucassouzavieira, como eu faço com o sample.py do arquivo anterior pra poder executar essa nova atualização?

**Comment by lucassouzavieira** [comment]
@jherfson, vou escrever alguns exemplos de uso do pacote e colocar aqui no repositório.

**Comment by jherfson** [comment]
@lucassouzavieira, vou ficar no aguardo.

**Comment by jherfson** [comment]
Ei @lucassouzavieira e os exemplos?
